In [2]:
import pandas as pd

reihanehs_table = pd.read_csv('/Users/brune/Downloads/BHI_with_Tween80 (1).csv', sep=";")
reihanehs_table

             Metabolite       BiGG
0             L-Alanine   ala__L_e
1            L-Arginine   arg__L_e
2          L-Asparagine   asn__L_e
3           L-Aspartate   asp__L_e
4            L-Cysteine   cys__L_e
5           L-Glutamate   glu__L_e
6           L-Glutamine   gln__L_e
7               Glycine      gly_e
8           L-Histidine   his__L_e
9          L-Isoleucine   ile__L_e
10            L-Leucine   leu__L_e
11             L-Lysine   lys__L_e
12         L-Methionine   met__L_e
13      L-Phenylalanine   phe__L_e
14            L-Proline   pro__L_e
15             L-Serine   ser__L_e
16          L-Threonine   thr__L_e
17         L-Tryptophan   trp__L_e
18           L-Tyrosine   tyr__L_e
19             L-Valine   val__L_e
20            D-Glucose   glc__D_e
21        Glycylglycine   glygly_e
22         Thiamin (B1)      thm_e
23      Riboflavin (B2)   ribflv_e
24  Nicotinate (niacin)      nac_e
25    PANTOTHENATE (B5)  pnto__R_e
26      Pyridoxine (B6)  pyridox_e
27          Biotin (B7)      btn_e
28      Folic acid (B9)      fol_e
29      Cobalamin (B12)     cbl1_e
30            lipid IVA   lipidA_e
31           Coenzyme A      coa_e
32               Sodium      na1_e
33             Chloride       cl_e
34            Potassium        k_e
35            Phosphate       pi_e
36             Ammonium      nh4_e
37              Sulfate      so4_e
38            Magnesium      mg2_e
39              Calcium      ca2_e
40           Iron (III)      fe2_e
41                 Zinc      zn2_e
42            Manganese      mn2_e
43               Copper      cu2_e
44               Cobalt  cobalt2_e
45            Molybdate     mobd_e
46               Oleate   ocdcea_e
47            Palmitate     hdca_e
48            Myristate    ttdca_e
49             Glycerol     glyc_e
50                 Urea     urea_e
51             Creatine     crtn_e
52              Choline     chol_e
53          L-Carnitine      crn_e
54            Adenosine      adn_e
55              Guanine      gua_e
56              Uridine      uri_e
57            Thymidine    thymd_e
58             Cytidine     cytd_e

In [3]:
from refinegems.classes import medium

m = medium.Medium("BHI", description="Brain Heart Infusion")
m

In [4]:
m.add_subset("CasA")

WARNING:root:Only one of the substance tables contains valid rows during combination.

In [5]:
m9 = medium.load_medium_from_db("M9")
m9.substance_table["name"].unique()
m.combine(m9, "+", inplace=True)

/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:409: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  to_add["flux"] = to_add["flux"].fillna(default_flux)

In [6]:
# adding substances part 1
m.add_substance_from_db("Thiamine")
m.add_substance_from_db("Riboflavin")
m.add_substance_from_db("Pyridine-3-carboxylate [Niacin]")
m.add_substance_from_db("3-[(2R)-2,4-Dihydroxy-3,3-dimethylbutanamido]propanoate [Pantothenate]")
m.add_substance_from_db("4,5-Bis(hydroxymethyl)-2-methylpyridin-3-ol [Pyridoxine]")
m.add_substance_from_db("N-(4-{[(2-amino-4-oxo-3,4-dihydropteridin-6-yl)methyl]amino}benzoyl)-L-glutamic acid [Folate]")
m.add_substance_from_db("Biotin")

m.add_substance_from_db("Coenzyme A")

# m.add_substance_from_db("Oleate") -> this comes from the extra

m.add_substance_from_db("Urea")
m.add_substance_from_db("Creatine")
m.add_substance_from_db("Choline")
m.add_substance_from_db("L-Carnitine")
m.add_substance_from_db("Adenosine")

In [7]:
# add substances part 2 
m.add_substance_from_db("Zinc(II) cation [Zn(2+)]")
m.add_substance_from_db("Manganese(II) cation [Mn(2+)]")
m.add_substance_from_db("Copper(II) cation [Cu(2+)]")
m.add_substance_from_db("Cobalt(II) cation [Co(2+)]")
m.add_substance_from_db("Tetraoxidomolybdate(VI) [Molybdate]")

m.add_substance_from_db("Glycerol")
m.add_substance_from_db("Uridine")
m.add_substance_from_db("Thymidine")
m.add_substance_from_db("Cytidine")

In [8]:
# add substances part 3 
m.add_substance_from_db("Iron(II) cation [Fe(2+)]")
m.add_substance_from_db("Iron(III) cation [Fe(3+)]")

In [9]:
# add substances part 4
m.add_substance_from_db("Cob(I)alamin")
m.add_substance_from_db("Cob(II)alamin")
m.add_substance_from_db("Vitamin B12")

In [10]:
# add substances part 5
m.add_substance_from_db("L-Asparagine")
m.add_substance_from_db("L-Cysteine")  
m.add_substance_from_db("L-Glutamine")

m.add_substance_from_db("Hexadecanoate [Palmitic acid]")
m.add_substance_from_db("Tetradecanoate") # myristate

In [11]:
still_missing = [_ for _ in reihanehs_table["Metabolite"] if not any(_ in x for x in m.substance_table["name"].unique())]
still_missing.remove("Thiamin (B1)")
still_missing.remove("Riboflavin (B2)")
still_missing.remove("Nicotinate (niacin)")
still_missing.remove("PANTOTHENATE (B5)")
still_missing.remove("Pyridoxine (B6)")
still_missing.remove("Biotin (B7)")
still_missing.remove("Folic acid (B9)")
still_missing.remove("Ammonium")
still_missing.remove("Palmitate")
still_missing.remove("Cobalamin (B12)")
still_missing.remove("Iron (III)")
still_missing.remove("Myristate")
still_missing

['Glycylglycine', 'lipid IVA', 'Oleate', 'Guanine']

In [12]:
[_ for _ in m.substance_table["name"].unique() if not any (x in _ for x in list(reihanehs_table["Metabolite"]))]

['L-Cystine',
 'Ammonia',
 'Dioxygen [O2]',
 'Hydrogen [H(+)]',
 'Water [H2O]',
 'Thiamine',
 'Riboflavin',
 'Pyridine-3-carboxylate [Niacin]',
 '3-[(2R)-2,4-Dihydroxy-3,3-dimethylbutanamido]propanoate [Pantothenate]',
 '4,5-Bis(hydroxymethyl)-2-methylpyridin-3-ol [Pyridoxine]',
 'N-(4-{[(2-amino-4-oxo-3,4-dihydropteridin-6-yl)methyl]amino}benzoyl)-L-glutamic acid [Folate]',
 'Biotin',
 'Iron(II) cation [Fe(2+)]',
 'Iron(III) cation [Fe(3+)]',
 'Cob(I)alamin',
 'Cob(II)alamin',
 'Vitamin B12',
 'Hexadecanoate [Palmitic acid]',
 'Tetradecanoate']

In [42]:
# create subset for Tween-80 (oleate source)
medium.add_subset_to_db(
    name = "Tween 80™",
    desc = "Culture medium additive Tween 80™ (oleate source)",
    subs_dict = {"Oleate":None},
)

In [ ]:
# Glycylglycine
name = "Glycylglycine"
formula = "C4H8N2O3"
annots = {
    "BiGG":"glygly",
    "CHEBI":[17201,5504, 14364, 24413],
    "KEGG":"C02037",
    "SEED":"cpd01391",
    "MetaNetX":"MNXM4002"
}

glygly = pd.DataFrame(
    {
        "name":name,
        "formula":formula,
        "flux":pd.NA,
        "source":None,
        "db_id":list(annots.values()),
        "db_type":list(annots.keys())
     }
    )
glygly = glygly.explode("db_id")
m.substance_table = pd.concat([ m.substance_table, glygly], ignore_index=True)
m.substance_table

# something went wrong when adding the new annotations 
# -> added them manually for glygly

/var/folders/xd/zl0vk7sj60xcc0zmc4k4mxxc0000gr/T/ipykernel_73841/2295488137.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  m.substance_table = pd.concat([ m.substance_table, glygly], ignore_index=True)

              name      formula  flux source     db_id   db_type
0          Glycine      C2H5NO2  0.22   None    C00037      KEGG
1          Glycine      C2H5NO2  0.22   None    MNXM29  MetaNetX
2          Glycine      C2H5NO2  0.22   None  cpd00033      SEED
3          Glycine      C2H5NO2  0.22   None       gly  BiGG+VMH
4        L-Cystine  C6H12N2O4S2  0.03   None   cysi__L      BiGG
..             ...          ...   ...    ...       ...       ...
242  Glycylglycine     C4H8N2O3   NaN   None     14364     CHEBI
243  Glycylglycine     C4H8N2O3   NaN   None     24413     CHEBI
244  Glycylglycine     C4H8N2O3   NaN   None    C02037      KEGG
245  Glycylglycine     C4H8N2O3   NaN   None  cpd01391      SEED
246  Glycylglycine     C4H8N2O3   NaN   None  MNXM4002  MetaNetX

[247 rows x 6 columns]

In [16]:
# set metadata
m.name = "BHI"
m.description = "Brain Heart Infusion (working progress)"
m.doi = "First attempt to create this medium in silico, based loosely on literature and mainly on experience as this is a complex medium"

# add medium to database 
medium.enter_medium_into_db(m)

Following similar entries have been found for the substance Vitamin B12.
(285, 'Vitamin B12', None)
Following similar entries have been found for the substance Vitamin B12.
(285, 'Vitamin B12', None)
Following similar entries have been found for the substance Vitamin B12.
(285, 'Vitamin B12', None)
Following similar entries have been found for the substance Vitamin B12.
(285, 'Vitamin B12', None)
Following similar entries have been found for the substance Glycylglycine.
(168, 'L-Asparagine', 'C4H8N2O3')
Medium BHI with ID 12 has been added to the database.

/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 138 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 164 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 166 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 169 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 175 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 178 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 180 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 182 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 183 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 188 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 189 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 190 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 192 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 194 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 195 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 196 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 56 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 75 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 81 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 102 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 120 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 150 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 201 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 232 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 235 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 251 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 258 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 286 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 270 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 246 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 240 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 25 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 66 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 334 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 281 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 83 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 289 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 204 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 90 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 89 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 269 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 156 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 157 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 87 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 88 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 285 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 168 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 173 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 176 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 147 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 268 already exists, skipped second assignment.
  warnings.warn(
/Users/brune/Documents/10_Code/refinegems/build/__editable__.refinegems-2.0.0b1-py3-none-any/refinegems/classes/medium.py:1522: UserWarning: Medium2substance connection 12 - 335 already exists, skipped second assignment.
  warnings.warn(

In [1]:
# update the database schema
from refinegems.classes import medium
medium.updated_db_to_schema("/Users/brune/Documents/10_Code/refinegems/src/refinegems/data/database")

Of interest -> new based on ou database

- L-Cystine
- Water
- Hydrogen
- Dioxygen

ask Reihaneh
- why lipid A? source?
- why guanine and not guanosine (parallel to the other three?)

missing in DB
- glygly